"""Convert the maze generated by the library into project models."""
from .models import Maze, Cell


class MazeAdapter:
    """Convert a generated maze into the project's Maze model."""

    def adapt(self, matrix: list[list[int]],
              entry: tuple[int, int],
              exit: tuple[int, int]) -> Maze:
        """Create a Maze instance from the generated maze data."""
        cells = []
        for y, row in enumerate(matrix):
            cell_row = []
            for x, value in enumerate(row):
                cell = self._adapt_cell(x, y, value)
                cell_row.append(cell)
            cells.append(cell_row)
        entry_x, entry_y = entry
        exit_x, exit_y = exit
        return Maze(
                    width=len(matrix[0]),
                    height=len(matrix),
                    cells=cells,
                    entry_cell=cells[entry_y][entry_x],
                    exit_cell=cells[exit_y][exit_x]
                    )

    def _adapt_cell(self, x: int, y: int, value: int) -> Cell:
        """Convert an encoded cell value into a Cell object."""

        north_open = bool(value & 1)
        east_open = bool(value & 2)
        south_open = bool(value & 4)
        west_open = bool(value & 8)
        return Cell(
                    x=x,
                    y=y,
                    north_open=north_open,
                    east_open=east_open,
                    south_open=south_open,
                    west_open=west_open
                )

