"""Convert the maze generated by the library into project models."""


from .models import Maze, Cell


class MazeAdapter:
    """Convert the external maze library output into project models."""

    def adapt(
        self,
        matrix: list[list[int]], 
        entry: tuple[int, int],
        exit: tuple[int, int]
    ) -> Maze:
        """Build a Maze from an encoded integer matrix.

        Args:
            matrix: 2D grid of encoded cell values.
            entry: (x, y) of the maze entry cell.
            exit: (x, y) of the maze exit cell.

        Returns:
            Fully populated Maze instance.
        """
        cells = []
        for y, row in enumerate(matrix):
            cell_row = []
            for x, value in enumerate(row):
                cell = self._adapt_cell(x, y, value)
                cell_row.append(cell)
            cells.append(cell_row)
        entry_x, entry_y = entry
        exit_x, exit_y = exit
        return Maze(
            width=len(matrix[0]),
            height=len(matrix),
            cells=cells,
            entry_cell=cells[entry_y][entry_x],
            exit_cell=cells[exit_y][exit_x]
        )

    def _adapt_cell(self, x: int, y: int, value: int) -> Cell:
        """Decode an integer cell value into a Cell instance.

        Args:
            x: Cell column.
            y: Cell row.
            value: Encoded wall bitmask (N=1, E=2, S=4, W=8).

        Returns:
            Cell with wall flags and walkability set.
        """
        north_wall = bool(value & 1)
        east_wall = bool(value & 2)
        south_wall = bool(value & 4)
        west_wall = bool(value & 8)
        return Cell(
            x=x,
            y=y,
            north_wall=north_wall,
            east_wall=east_wall,
            south_wall=south_wall,
            west_wall=west_wall,
            walkable=value != 15
        )
